# Generated by Django 4.2.11 on 2026-05-10 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('login', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('access_token_enc', models.TextField()),
                ('scopes', models.TextField(blank=True, default='')),
                ('needs_reauth', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
