# Generated by Django 4.2.11 on 2026-05-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_repository_first_ingested_by_repository_is_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cloning', 'Cloning'), ('parsing', 'Parsing'), ('embedding', 'Embedding'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
